# Generated by Django 4.1.10 on 2024-09-05 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_accepted',
            field=models.BooleanField(null=True, verbose_name='Согласие на обработку персональных данных'),
        ),
    ]
