# Generated by Django 5.2.9 on 2025-12-29 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customuser_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='personal_data_trasfer_accepted',
            field=models.BooleanField(blank=True, null=True, verbose_name='Согласие на передачу персональных данных третьим лицам'),
        ),
    ]
