# Generated by Django 5.2.9 on 2025-12-29 21:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_personal_data_trasfer_accepted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='personal_data_trasfer_accepted',
            new_name='personal_data_transfer_accepted',
        ),
    ]
